### ISSUE TITLE
Failure with dev purrr

### ISSUE THREAD

**Issue by hadley** [rubenarslan/codebook#73] opened 2022-10-28 12:24 UTC
With the dev version of purrr, the following code fails:

```R
library(codebook)

num <- haven::read_spss(test_path("different-missings.sav"), user_na = TRUE)
attributes(num[, 3][[1]])$na_values <- NULL
attributes(num[, 3][[1]])$label <- ""
attributes(num[, 4][[1]])$label <- ""

num <- detect_missing(num,
  negative_values_are_missing = FALSE,
  only_labelled = FALSE,
  use_labelled_spss = TRUE
)

num <- detect_missing(num,
  negative_values_are_missing = TRUE,
  only_labelled = FALSE
)
```

I've tried to dig a bit into `detect_missing()` but I can't figure out if it's something wrong in the first or second call to `detect_missing()`. I'm happy to dig in a bit further, but I really need some help from you.

**Comment by rubenarslan** [comment] 2024-10-14 08:12
Sorry for the extremely late response. I cannot reproduce the error with purrr 1.0.2 and the output is correct. Not sure what was up, so I'm closing this issue.

**Closed as completed by rubenarslan** 2024-10-14 08:12 UTC
